{
 "title": "Speed Test",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "database", "query": "influxdb" },
   {
    "name": "TestServer",
    "label": "Test Server",
    "query": "SHOW TAG VALUES WITH KEY = \"server-name\""
   },
   {
    "name": "hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"hostname\""
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "speedtest-results",
     "select": [
      [
       { "params": [ "download-bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "upload-bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server-name", "operator": "=~", "value": "/^$TestServer$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Download",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "speedtest-results",
     "query": "SELECT \"download-bandwidth\" AS \"download\" FROM \"speedtest-results\" WHERE (\"server-name\" =~ /^$TestServer$/ AND \"hostname\" =~ /^$hostname$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "download-bandwidth" ], "type": "field" },
       { "params": [ "download" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server-name", "operator": "=~", "value": "/^$TestServer$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Upload",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "speedtest-results",
     "select": [
      [
       { "params": [ "upload-bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server-name", "operator": "=~", "value": "/^$TestServer$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Min Download",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "measurement": "speedtest-results",
     "select": [
      [
       { "params": [ "download-bandwidth" ], "type": "field" },
       { "params": [ "download" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server-name", "operator": "=~", "value": "/^$TestServer$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Min Upload",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "measurement": "speedtest-results",
     "select": [
      [
       { "params": [ "upload-bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server-name", "operator": "=~", "value": "/^$TestServer$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Download Result",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "server-name" ], "type": "tag" }
     ],
     "measurement": "speedtest-results",
     "query": "SELECT \"hostname\" as Device, \"server-location\" as Location, \"server-name\" as Server, \"server-id\", \"url\", \"Ping\", max(\"Download\") AS \"Download\", \"Upload\", \"Combined\", \"Public IP\" FROM (SELECT \"download-bandwidth\" + \"upload-bandwidth\" AS Combined, \"result-url\" AS \"url\", \"latency\" AS \"Ping\", \"download-bandwidth\" AS \"Download\", \"upload-bandwidth\" AS \"Upload\", \"external-IP\" AS \"Public IP\" FROM \"speedtest-results\" WHERE (\"server-name\" =~ /^$TestServer$/ AND \"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"hostname\", \"server-name\", \"server-location\", \"server-id\")",
     "select": [
      [
       { "params": [ "result-url" ], "type": "field" },
       { "params": [ "url" ], "type": "alias" }
      ],
      [
       { "params": [ "latency" ], "type": "field" },
       { "params": [ "ping" ], "type": "alias" }
      ],
      [
       { "params": [ "download-bandwidth" ], "type": "field" },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "upload-bandwidth" ], "type": "field" },
       { "params": [ "Upload" ], "type": "alias" }
      ],
      [
       { "params": [ "external-IP" ], "type": "field" },
       { "params": [ "Public IP" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Upload Result",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "server-name" ], "type": "tag" }
     ],
     "measurement": "speedtest-results",
     "query": "SELECT \"hostname\" as Device, \"server-location\" as Location, \"server-name\" as Server, \"server-id\", \"url\", \"Ping\", \"Download\", max(\"Upload\") as Upload, \"Combined\", \"Public IP\" FROM (SELECT \"download-bandwidth\" + \"upload-bandwidth\" AS Combined, \"result-url\" AS \"url\", \"latency\" AS \"Ping\", \"download-bandwidth\" AS \"Download\", \"upload-bandwidth\" AS \"Upload\", \"external-IP\" AS \"Public IP\" FROM \"speedtest-results\" WHERE (\"server-name\" =~ /^$TestServer$/ AND \"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"hostname\", \"server-name\", \"server-location\", \"server-id\")",
     "select": [
      [
       { "params": [ "result-url" ], "type": "field" },
       { "params": [ "url" ], "type": "alias" }
      ],
      [
       { "params": [ "latency" ], "type": "field" },
       { "params": [ "ping" ], "type": "alias" }
      ],
      [
       { "params": [ "download-bandwidth" ], "type": "field" },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "upload-bandwidth" ], "type": "field" },
       { "params": [ "Upload" ], "type": "alias" }
      ],
      [
       { "params": [ "external-IP" ], "type": "field" },
       { "params": [ "Public IP" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Best Overall Result",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "server-name" ], "type": "tag" }
     ],
     "measurement": "speedtest-results",
     "query": "SELECT \"hostname\" as Device, \"server-location\" as Location, \"server-name\" as Server, \"server-id\", \"url\", \"Ping\", \"Download\", \"Upload\", max(Combined) AS \"Combined\", \"Public IP\" FROM (SELECT \"download-bandwidth\" + \"upload-bandwidth\" AS Combined, \"result-url\" AS \"url\", \"latency\" AS \"Ping\", \"download-bandwidth\" AS \"Download\", \"upload-bandwidth\" AS \"Upload\", \"external-IP\" AS \"Public IP\" FROM \"speedtest-results\" WHERE (\"server-name\" =~ /^$TestServer$/ AND \"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"hostname\", \"server-name\", \"server-location\", \"server-id\")\n",
     "select": [
      [
       { "params": [ "result-url" ], "type": "field" },
       { "params": [ "url" ], "type": "alias" }
      ],
      [
       { "params": [ "latency" ], "type": "field" },
       { "params": [ "ping" ], "type": "alias" }
      ],
      [
       { "params": [ "download-bandwidth" ], "type": "field" },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "upload-bandwidth" ], "type": "field" },
       { "params": [ "Upload" ], "type": "alias" }
      ],
      [
       { "params": [ "external-IP" ], "type": "field" },
       { "params": [ "Public IP" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Results",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "server-name" ], "type": "tag" }
     ],
     "measurement": "speedtest-results",
     "query": "SELECT \"hostname\" as Device, \"server-location\" as Location, \"server-name\" as Server, \"server-id\", \"url\", \"Ping\", \"Download\", \"Upload\", \"Combined\", \"Public IP\" FROM (SELECT \"result-url\" AS \"url\", \"latency\" AS \"Ping\", \"download-bandwidth\" AS \"Download\", \"upload-bandwidth\" AS \"Upload\", \"download-bandwidth\" + \"upload-bandwidth\" AS \"Combined\", \"external-IP\" AS \"Public IP\" FROM \"speedtest-results\" WHERE (\"server-name\" =~ /^$TestServer$/ AND \"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"hostname\", \"server-name\", \"server-location\", \"server-id\")",
     "select": [
      [
       { "params": [ "result-url" ], "type": "field" },
       { "params": [ "url" ], "type": "alias" }
      ],
      [
       { "params": [ "latency" ], "type": "field" },
       { "params": [ "ping" ], "type": "alias" }
      ],
      [
       { "params": [ "download-bandwidth" ], "type": "field" },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "upload-bandwidth" ], "type": "field" },
       { "params": [ "Upload" ], "type": "alias" }
      ],
      [
       { "params": [ "external-IP" ], "type": "field" },
       { "params": [ "Public IP" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "speedtest-results",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Latency" ], "type": "alias" }
      ],
      [
       { "params": [ "jitter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Jitter" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server-name", "operator": "=~", "value": "/^$TestServer$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}